# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CentralityiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CentralityiOS
  pod 'Parse'
  pod 'FSCalendar'
  pod 'DateTools'
  pod 'IQKeyboardManager'
  pod 'Charts'

  target 'CentralityiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CentralityiOSUITests' do
    # Pods for testing
  end

end
